name: CI

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.12'

     - name: Install Poetry
       uses: snok/install-poetry@v1
       with:
         version: 1.7.1

     - name: Install dependencies
       run: |
         poetry install

 docker:
   needs: test
   if: github.ref == 'refs/heads/main'
   runs-on: ubuntu-latest
   env:
     DOCKER_IMAGE: wandb-sync
     DOCKER_TAG: latest

   steps:
     - uses: actions/checkout@v4

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3

     - name: Login to GitHub Container Registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Build and push
       uses: docker/build-push-action@v5
       with:
         push: true
         tags: ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
         cache-from: type=gha
         cache-to: type=gha,mode=max